### ISSUE TITLE
open-source license?

### ISSUE THREAD

**Issue by sjoerd222888** [benhutchins/docker-taiga#33]
What is the license of this repository? I see no license attached, so practically if I understand it correctly I am not allowed to use the code without permission. Could please elaborate the license of this repository?
References: [What's the default license of code published at GitHub?](https://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github)

**Comment by zicklag** [comment]
I would greatly appreciate having the license specified. I didn't realize that this repository didn't have a license. That makes a big difference to me, because I need the ability to change the containers that I use if need be. I'll have to use something else if I can't legally modify and use this container. :frowning_face:

**Comment by zicklag** [comment]
Thanks! :smiley:

**Comment by sjoerd222888** [comment]
Thus GPL. Thanks :-).
